"""adding url-type and image_url

Revision ID: ef75bfba0d90
Revises: 82eab18f3a71
Create Date: 2021-12-30 01:45:44.214851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef75bfba0d90'
down_revision = '82eab18f3a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('url_type', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_url')
    op.drop_column('posts', 'url_type')
    # ### end Alembic commands ###
